### ISSUE TITLE
About the Log-likelihood score

### ISSUE THREAD

**Issue by lqh52** [Jeanselme/SuMo-net#1]
Hi, thanks a lot for your beautiful repo, it really helped me. However, I'm quite confuse about the log-likelihood score reported in their paper because I can not re-produce it with your code. Can you please explain to me? Many thanks

**Comment by Jeanselme** [comment]
Hello, thank you for your question!
I updated the derivative computation as I was taking the mean instead of the sum. This sometimes leads to a negative log likelihood (a likelihood > 1)
